from datetime import datetime

from sqlalchemy import Column, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class Market(Base):
    """Polymarket football market."""

    __tablename__ = "markets"

    id = Column(Integer, primary_key=True, autoincrement=True)
    condition_id = Column(String, unique=True, nullable=False)
    question = Column(Text, nullable=False)
    slug = Column(String)
    sport = Column(String, default="football")  # football, basketball, mma, etc.
    league = Column(String)  # EPL, LaLiga, SerieA, Bundesliga, Ligue1, UCL, WorldCup
    market_type = Column(String, default="binary")  # binary, multi_outcome
    home_team = Column(String)
    away_team = Column(String)
    match_date = Column(DateTime)
    yes_token_id = Column(String)
    no_token_id = Column(String)
    active = Column(Integer, default=1)
    volume = Column(Float, default=0.0)
    liquidity = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Price(Base):
    """Time-series price data for markets."""

    __tablename__ = "prices"

    id = Column(Integer, primary_key=True, autoincrement=True)
    condition_id = Column(String, nullable=False, index=True)
    yes_price = Column(Float, nullable=False)  # 0-1, Polymarket implied prob
    no_price = Column(Float)
    bid = Column(Float)
    ask = Column(Float)
    spread = Column(Float)
    volume_1h = Column(Float)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)


class Signal(Base):
    """Trading signals generated by strategies."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    condition_id = Column(String, nullable=False, index=True)
    strategy = Column(String, nullable=False)  # triple_odds, volume_spike, clv_trend
    direction = Column(String, nullable=False)  # BUY_YES, BUY_NO
    confidence = Column(Float, nullable=False)
    suggested_size = Column(Float)

    # Three-way odds comparison
    poly_prob = Column(Float)
    book_prob = Column(Float)
    ai_prob = Column(Float)
    consensus_delta = Column(Float)

    status = Column(String, default="pending")  # pending, confirmed, executed, expired
    created_at = Column(DateTime, default=datetime.utcnow)


class AIReport(Base):
    """AI match analysis reports."""

    __tablename__ = "ai_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    condition_id = Column(String, nullable=False, index=True)
    home_team = Column(String)
    away_team = Column(String)
    prediction = Column(String)  # HOME_WIN, DRAW, AWAY_WIN
    confidence = Column(Float)
    home_win_prob = Column(Float)
    draw_prob = Column(Float)
    away_win_prob = Column(Float)
    key_factors = Column(Text)  # JSON array
    reasoning = Column(Text)
    raw_response = Column(Text)  # Full LLM response
    model = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)


class Position(Base):
    """Active and closed positions."""

    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    condition_id = Column(String, nullable=False, index=True)
    side = Column(String, nullable=False)  # YES, NO
    size = Column(Float, nullable=False)  # USDC
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float)
    pnl = Column(Float, default=0.0)
    status = Column(String, default="open")  # open, closed, settled
    signal_id = Column(Integer)
    opened_at = Column(DateTime, default=datetime.utcnow)
    closed_at = Column(DateTime)
